### ISSUE TITLE
New to UVCDAT, many problems?

### ISSUE THREAD

**Issue by lguandiq** [CDAT/cdat-old-site#8]
<img width="1280" alt="screen shot 2017-03-28 at 3 38 56 pm" src="https://cloud.githubusercontent.com/assets/26879786/24623624/e591c19a-185d-11e7-993b-03f65801cc21.png">
<img width="1280" alt="screen shot 2017-03-28 at 3 42 20 pm" src="https://cloud.githubusercontent.com/assets/26879786/24623635/ec0c2c0e-185d-11e7-82e7-7c5f6bbe8dfc.png">
I just downloaded UV-CDAT onto my macbook after my professor told me that it is something he wants me to learn to use. It was great on his computer, however i've been having a lot of issues on my computer. The only thing I have tried to do was change one of the isofill plots and I keep changing the settings in the configuration panel but the settings simply go back to the way they were before. I'm trying to change the level ranges and colors but it just reverts to whatever it was before. Also, I keep getting a pop up shown in the picture. I continue saving but it shows up at random and I can't seem to stop it. I was wondering if this was a common issue. I couldn't get onto the website to search up these errors because i keep getting certificate errors. I was wondering if it was because the execution on a macbook doesn't work as well as linux. 
Hope you can help me solve these issues!

**Comment by mattben** [comment]
this repo is a legacy website. You'll want to post to https://github.com/UV-CDAT/uvcdat/issues.

**Comment by doutriaux1** [comment]
@mattben we're still trying to support existing issues with vistrails until we switch to vcdat. I'm trying to help @lguandiq on this.

**Comment by mattben** [comment]
@doutriaux1 perfect I was just trying to direct them to the correct place.
